### ISSUE TITLE
有空额时识别出来的姓名不对，希望能修复

### ISSUE THREAD

**Issue by linwb2006** [ldwonday/zh-address-parse#1]
江苏省 苏州市 平江区 干将东路608号江苏大厦3楼 215000 徐天宇 13962162160
识别出来的姓名不对，希望能修复

**Comment by ldwonday** [comment]
已经修复，另外注意你的错别字，空格不是空额，吴江区不是平江区！！~感谢您的关注！~

**Comment by linwb2006** [comment]
效率高，太感谢了，昨晚很抱歉打错字。
官方的苏州市的行政区域参考：
https://www.xzqy.net/320500000000.htm
有吴江区  也有 平江区

另外建议把行政区域数据js分离出来，方便更新维护。

**Comment by ldwonday** [comment]
@linwb2006 
具体的省市区可以参考：[http://www.mca.gov.cn/article/sj/xzqh/2019/2019/201911250933.html](http://www.mca.gov.cn/article/sj/xzqh/2019/2019/201911250933.html)
这是政府提供的，是最权威的，里面有就有没有就没有。
