### ISSUE TITLE
打算试着开个restful的接口，没有成功

### ISSUE THREAD

**Issue by ecmsglobal** [ldwonday/zh-address-parse#13]
git上十几个解析地址的项目，试下来这个是最靠谱的。我们的项目是java的，需要开个restful的接口获取结果。无奈本人实在是前端水平太差，没有成功。

哪位老大肯出手帮助一下吗，万分感谢。

**Comment by ecmsglobal** [comment]
我先说一下我怎么弄的：
0. 按照文档，npm i zh-address-parse -s。然后npm s是能看到结果的：
```
E:\git-root\zh-address-parse>npm s zh-address-parse
NAME                      | DESCRIPTION          | AUTHOR          | DATE       | VERSION  | KEYWORDS
zh-address-parse          | chinese address…     | =wangbagang     | 2020-04-28 | 1.2.6    |
```
1. 在根目录增加了一个main.js，引入了express，做服务。node main.js是可以启动的
2. 导入之后，就启动报错，说找不到module
```
E:\git-root\zh-address-parse>node main.js
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module 'zh-address-parse'
Require stack:
- E:\git-root\zh-address-parse\main.js
```
3. 直接从路径import脚本文件，报错说不能引入
```
E:\git-root\zh-address-parse\main.js:3
import AddressParse from './dist/zh-address-parse.min.js'
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

急求解决方法。

**Comment by ldwonday** [comment]
node环境下不能用import语法，import是ES6的语法，要用webpack+babel转换。不会用webpack+babel那么就直接用node的commonjs语法：var AddressParse = require('zh-address-parse') 或者 require('./dist/zh-address-parse.min.js')方式引入。
