### ISSUE TITLE
希望能改进地址的识别模糊化，很多地址识别太离谱了

### ISSUE THREAD

**Issue by linwb2006** [ldwonday/zh-address-parse#2]
希望能改进地址的识别模糊化，很多地址识别太离谱了，地址的识别要模糊化不要太遵守地址列表。
看看一下地址：
王小梅15273551234湖南省郴州市桂东县桂东县清泉镇
莫席辉13667721234广西壮族自治区柳州市柳北区跃进路42号4栋20楼
韩仁伟,18555605568,安徽省安庆市太湖县新仓镇，塔山村，前进组

**Comment by ldwonday** [comment]
@linwb2006 感谢，这个由于地区的识别从0开始导致的。已经修复，以后识别出不出来，试试换树查找方式，默认是正则！欢迎有问题继续提issues！~另外你好像还没有点赞哦！~

**Comment by ldwonday** [comment]
欢迎star哦
