### ISSUE TITLE
是否是智能识别？

### ISSUE THREAD

**Issue by Audrena** [ldwonday/zh-address-parse#23]
想问一下，这个是否能够调用百度地图，来进行缺失信息的补充。

**Comment by ldwonday** [comment]
可以举个例子吗？

**Comment by Audrena** [comment]
比如填写的地址：北京阿里巴巴，通过百度地图接口识别成北京-北京市-朝阳区-望京街道阿里巴巴，
在地址解析的基础上实现智能匹配搜索，自动补充缺失的地址信息

**Comment by ldwonday** [comment]
这个搞的有点复杂了。暂不支持的哈！~

**Comment by Audrena** [comment]
哈哈，好的，感谢。
