### ISSUE TITLE
某些地区只能识别的时候会出现内存溢出的错误

### ISSUE THREAD

**Issue by zjk270997340** [ldwonday/zh-address-parse#24]
重庆市南岸区兰花路兰湖天小区
邓先森
15808888888
这个地址粘贴自动识别之后，直接会提示内存溢出

**Comment by ldwonday** [comment]
可能死循环了，我看下咋回事！

**Comment by ldwonday** [comment]
我测了是谷歌浏览器和safar都没问题，你能提供下更详细的信息么？浏览器标识？什么环境？

**Comment by zjk270997340** [comment]
在小程序中使用的，开发者工具以及手机中都会出现这个问题

**Comment by zjk270997340** [comment]
主要是重庆地区有问题，其他的直辖市没有问题

**Comment by ldwonday** [comment]
![image](https://user-images.githubusercontent.com/4630157/97983937-fdb8f880-1e10-11eb-9b01-423a5cfbbfbc.png)
小程序我也测试过了，没有问题的呀。

**Comment by zjk270997340** [comment]
嗯嗯，我看下我自己的那部分
