### ISSUE TITLE
校验非常不准

### ISSUE THREAD

**Issue by 18616372930** [ldwonday/zh-address-parse#26]
![image](https://user-images.githubusercontent.com/74960000/100304463-c7b70080-2fd9-11eb-92f6-2a42500e8009.png)

张彤，15776993213，黑龙江省 大兴安岭地区 加格达奇区 铁路南小区29号楼4单元5658sf

上面2个都不行。

**Comment by ldwonday** [comment]
![image](https://user-images.githubusercontent.com/4630157/100330068-6eff5c00-3009-11eb-9df8-fdc9c6c1aa73.png)

**Comment by 18616372930** [comment]
如果没有县 就不显示了么

**Comment by ldwonday** [comment]
已修复！~谢谢！~
