### ISSUE TITLE
没有区县统统不行

### ISSUE THREAD

**Issue by 18616372930** [ldwonday/zh-address-parse#27]
广东省

**Comment by 18616372930** [comment]
蔡丽凤,18019628350,江苏省盐城市其它区神州路御景湾7#1104
孙晴,18027212214,广东省东莞市沙田镇稔州生喜便利店

**Comment by 18616372930** [comment]
我评论的都不行。 有点急。麻烦看下

**Comment by 18616372930** [comment]
@ldwonday

**Comment by ldwonday** [comment]
@18616372930 好，我看下

**Comment by 18616372930** [comment]
![image](https://user-images.githubusercontent.com/74960000/100330051-69a21180-3009-11eb-9fa3-67d30ec433ad.png)

@ldwonday  麻烦看下这里

**Comment by ldwonday** [comment]
能复制下吗？

**Comment by ldwonday** [comment]
已修复！谢谢！~
