### ISSUE TITLE
你好，报一个问题

### ISSUE THREAD

**Issue by YChao** [ldwonday/zh-address-parse#3]
深圳市罗湖区凤凰路中山花园1栋582室，刘蓝琴，电話13111111111
这个地址是你自己写在上面的，然后都不对，是不是要把“电话”这种关键字先剔除掉啊

**Comment by ldwonday** [comment]
@YChao 电话这是繁体字。过滤条件里面没有加，想要过滤繁体字，自己可以在代码里面可以加的。简体电话已经添加过滤条件了。

**Comment by ldwonday** [comment]
@YChao 文档已更新，新增参数textFilter，可自行设置过滤字段！
