### ISSUE TITLE
不考虑加个参考链接吗？

### ISSUE THREAD

**Issue by wzc570738205** [ldwonday/zh-address-parse#34]
**代码参考烦请加个署名**
[wzc570738205/smartParsePro](https://github.com/wzc570738205/smartParsePro)

**Comment by ldwonday** [comment]
@wzc570738205 你把代码拉下来对比下，看看有多少是一样的，超过40%我就说参考你的了好吧。

**Comment by wzc570738205** [comment]
我开发2.0的时候你加群，加我qq，说参考我的代码自己开发了一版。自己去翻翻自己的第三次commit

**Comment by wzc570738205** [comment]
你知道这么事情就行了，不和你做无意义的争论

**Comment by ldwonday** [comment]
@wzc570738205  你也是够无聊，不好好提高自己代码的识别率，跑过来就为了这个事情，我的实现方式和你的代码相差万里，你跑过来让我加个参考，如果真的如你所说有参考你的代码我自然会加。
