### ISSUE TITLE
两个识别问题

### ISSUE THREAD

**Issue by NetRube** [ldwonday/zh-address-parse#39]
1。地址前面有“中国”或其它文字会被识别到“name”里面去～
2。区县后面字数如果少于中文名最大长度会被识别到“name”里面去～如“江西省抚州市临川区公安宿舍”和“辽宁省盘锦市盘山县东郭镇”

**Comment by ldwonday** [comment]
可以举几个例子么？

**Comment by NetRube** [comment]
江西省抚州市临川区公安宿舍
识别结果
phone：
province：江西省
city：抚州市
area：临川区
detail：
name：公安宿舍
postalCode：

辽宁省盘锦市盘山县东郭镇
识别结果
phone：
province：辽宁省
city：盘锦市
area：盘山县
detail：
name：东郭镇
postalCode：
