### ISSUE TITLE
地区未识别出来

### ISSUE THREAD

**Issue by MoondanceZ** [ldwonday/zh-address-parse#46]
姓名：张三 地址：云南迪庆州德钦县升平镇 214国道西50米梅里雪山国家公园-雾浓顶景区润境梅里设计师酒店 13911111111

phone：13911111111
province：云南省
city：迪庆藏族自治州
area：
detail：214国道西50米梅里雪山国家公园-雾浓顶景区润境梅里设计师酒店州德钦县升平镇
name：张三
postalCode：

少了 area

**Comment by ldwonday** [comment]
迪庆州在国家统计局哪里是：迪庆藏族自治州，只写迪庆州会导致失败的。建议：
姓名：张三 地址：云南迪庆藏族自治州德钦县升平镇 214国道西50米梅里雪山国家公园-雾浓顶景区润境梅里设计师酒店  13911111111
或者
姓名：张三 地址：云南德钦县升平镇 214国道西50米梅里雪山国家公园-雾浓顶景区润境梅里设计师酒店  13911111111
