### ISSUE TITLE
无法解析市级县

### ISSUE THREAD

**Issue by wutouqishi** [ldwonday/zh-address-parse#5]
如 重庆市 垫江县 太平镇
province：重庆市
city：县
area：垫江县

**Comment by ldwonday** [comment]
其实这个不是无法解析，是解析对的。具体原因看[http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2018/50.html](http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2018/50.html)国家统计局是这样子的。重庆市的下一级是县然后才是垫江县。但是这又不符合大家的基本写法，没人会写：重庆市县垫江县，后面我会看怎么处理下！

**Comment by ldwonday** [comment]
@wutouqishi 原来的统计局的数据很多无用的，现在自己写了一个解析的。你的问题解决了！~
