### ISSUE TITLE
您好 手机号匹配稍微有些瑕疵，请问我该怎么修改？

### ISSUE THREAD

**Issue by wapffu** [ldwonday/zh-address-parse#56]
您好 手机号匹配稍微有些瑕疵，请问我该怎么修改？ 
比如这种格式（200801000001，张三，13688888888，广东省 深圳市 福田区 花花花路888号）  就会把订单号匹配成手机号，
JS文件咋修改呢 有没开发版

**Comment by ldwonday** [comment]
已修复哈

**Comment by ldwonday** [comment]
可以升级到1.3.11，识别更精准了，去掉了纯数字（订单编号之类的干扰）了
