### ISSUE TITLE
座机是还不支持识别吗，能否增加座机识别？

### ISSUE THREAD

**Issue by x-j-l** [ldwonday/zh-address-parse#57]
例如以下：
徐志摩0212222333上海市崇明区45-5号
徐志摩021-2222333上海市崇明区45-5号
徐志摩059122223333上海市崇明区45-5号
徐志摩0591-22223333上海市崇明区45-5号

**Comment by ldwonday** [comment]
座机不支持的，因为感觉这个场景太少了，可以自己在调用parse方法前先对字符串用正则过滤下座机号。
