### ISSUE TITLE
直辖市地址解析失败

### ISSUE THREAD

**Issue by mingjunChan** [ldwonday/zh-address-parse#6]
使用测试地址：https://ldwonday.github.io/zh-address-parse/
上海市黄浦区瞿溪路1032弄3号103
**预期结果**
province：上海市
city：上海市
area：黄浦区
detail：瞿溪路1032弄3号103
……
**实际结果**
province：上海市
city：徐汇区
area：
……

有如地址"重庆市涪陵区荔枝街道天籁城12栋29-10"，也得不到预期结果

需要java语言解析^_^

**Comment by ldwonday** [comment]
@mingjunChan 本质不是解析失败，地址json的问题，也不能说问题，有的人希望是下面的结果，有的人希望是你这样子的解析结果！~大部分是你这样子的解析结果！~
