### ISSUE TITLE
关于直辖市没办法识别

### ISSUE THREAD

**Issue by qq690712575** [ldwonday/zh-address-parse#74]
如上海市清浦区xxx
只识别到 省的字段是上海市，市的字段没识别出来，然后详细里面直接取了区+地址

**Comment by lukesyy** [comment]
> 如上海市清浦区xxx 只识别到 省的字段是上海市，市的字段没识别出来，然后详细里面直接取了区+地址

上海市青浦区xxx

**Comment by qq690712575** [comment]
但是区变了详细地址里面的内容了
省是上海
城市为空
区也为空
详细地址变了 青浦区xxxx

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: lukes ***@***.***>
发送时间: Tuesday, April 25, 2023 11:01:19 AM
收件人: ldwonday/zh-address-parse ***@***.***>
抄送: Jianle Chen ***@***.***>; Author ***@***.***>
主题: Re: [ldwonday/zh-address-parse] 关于直辖市没办法识别 (Issue #74)


如上海市清浦区xxx 只识别到 省的字段是上海市，市的字段没识别出来，然后详细里面直接取了区+地址

上海市青浦区xxx

―

**Comment by ldwonday** [comment]
2020年的国家统计局代码里没有清浦区

**Comment by qq690712575** [comment]
这样啊谢谢了 ，我看看有没得处理下。提交上来

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: ldwonday ***@***.***>
发送时间: Monday, May 8, 2023 10:56:18 AM
收件人: ldwonday/zh-address-parse ***@***.***>
抄送: Jianle Chen ***@***.***>; Author ***@***.***>
主题: Re: [ldwonday/zh-address-parse] 关于直辖市没办法识别 (Issue #74)


2020年的国家统计局代码里没有清浦区

―

**Comment by lukesyy** [comment]
没啥好修的  你自己打错了字了 青浦 不是 清浦

**Comment by ldwonday** [comment]
![image](https://user-images.githubusercontent.com/4630157/236725346-997091ac-5f4b-420e-a642-941f37bfa57b.png)
青浦区是没有问题的。

**Comment by qq690712575** [comment]
🥹别人告诉我的 我也没了解过

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: lukes ***@***.***>
发送时间: Monday, May 8, 2023 11:07:36 AM
收件人: ldwonday/zh-address-parse ***@***.***>
抄送: Jianle Chen ***@***.***>; Author ***@***.***>
主题: Re: [ldwonday/zh-address-parse] 关于直辖市没办法识别 (Issue #74)


没啥好修的 你自己打错了字了 青浦 不是 清浦
