### ISSUE TITLE
无法正确识别东莞市、中山市这类直接下辖乡镇街道的城市信息

### ISSUE THREAD

**Issue by DEEMO101** [ldwonday/zh-address-parse#75]
“广东省东莞市塘厦镇” 错误的将塘厦镇识别为名称（name）

**Comment by ldwonday** [comment]
不包含镇的解析的，如果要包含镇的解析建议自己改造下代码。另外如果给出全地址识别是没有问题的例如：王宫雪 广东省东莞市塘厦镇 13311111111

**Comment by DEEMO101** [comment]
> 不包含镇的解析的，如果要包含镇的解析建议自己改造下代码。另外如果给出全地址识别是没有问题的例如：王宫雪 广东省东莞市塘厦镇新安街道 13311111111

好的，我已经添加了数据将这种直辖镇街区识别为area，我看了数据来源确实也只包含区县及以上的行政区划数据😋
