### ISSUE TITLE
建议以 npm  package 形式发布

### ISSUE THREAD

**Issue by shiny** [ldwonday/zh-address-parse#8]
建议提供 npm 包，以便于 vue/react 环境下使用。

**Comment by ldwonday** [comment]
已发布npm！

**Comment by fuuqiu** [comment]
引入 ./dict方式一直报错  npm install zh-....

**Comment by ldwonday** [comment]
@fuuqiu 贴一个完成错误过来！

**Comment by fuuqiu** [comment]
> @fuuqiu贴一个完成错误过来！

This relative module was not found:

* ./dist/zh-address-parse.min.js in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/orders/AddOrder.vue?vue&type=script&lang=js&

**Comment by fuuqiu** [comment]
看了下 pack json 
.......
 "zh-address-parse": {
      "version": "1.2.6",
      "resolved": "https://registry.npmjs.org/zh-address-parse/-/zh-address-parse-1.2.6.tgz",
      "integrity": "sha512-sIOuiJdg==",
      "requires": {
        "jquery": "^3.4.1",
        "kind-of": ">=6.0.3",
        "lodash": "4.17.15",
        "minimist": ">=0.2.1",
        "segmentit": "^2.0.3"
      }


所以引用时 import AddressParse from 'zh-address-parse' 即可

**Comment by ldwonday** [comment]
@fuuqiu 感觉这个不是bug，应该是你项目配置的问题吧。

**Comment by ldwonday** [comment]
安装后试着重新运行下项目，看你这个开启了loader的cache！

**Comment by shiny** [comment]
挺好使，简单的示例：

```javascript
const AddressParse = require('zh-address-parse')
const parseResult = AddressParse('浙江省杭州市江干区听涛路999号')
console.log(parseResult)
/** 结果示例：
{
  phone: '',
  province: '浙江省',
  city: '杭州市',
  area: '江干区',
  detail: '听涛路999号',
  name: '',
  postalCode: ''
}

**/
```
